import GameList from '@/components/GameList/GameList';
import { GlobalStyle } from '@/styles/globals';
import Head from 'next/head';
import { Inter } from 'next/font/google';

const inter = Inter({
   subsets: ['latin'],
   display: 'swap',
});

export default function Home({}: object) {
   // const [isLoad, setIsload] = useState(false);
   const pages = [1];

   // if (!isLoad) {
   //    return <p>CARREGANDO...</p>;
   // }

   return (
      <>
         <GlobalStyle />
         <Head>
            <title>GAME APP | HOME</title>
            <meta name='description' content='Generated by create next app' />
            <meta
               name='viewport'
               content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <main className={inter.className}>
            {pages.map((page) => (
               <>
                  <GameList page={page} />
               </>
            ))}
         </main>
      </>
   );
}
