import { GlobalStyle } from '@/styles/globals';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useEffect, useState } from 'react';

interface IGameProps {
   id: number;
   name: string;
   background_image: string;
}

export default function Home({}: object) {
   const [isLoad, setIsload] = useState(false);
   const [data, setData] = useState<Array<IGameProps>>();

   useEffect(() => {
      async function getGames() {
         try {
            fetch('/api/games')
               .then((res) => res.json())
               .then((data) => {
                  setData(data);
                  setIsload(true);
               });
         } catch (error) {
            console.error(error);
         }
      }

      getGames();
   }, []);
   if (!isLoad) {
      return <p>CARREGANDO...</p>;
   }

   return (
      <>
         <GlobalStyle />
         <Head>
            <title>GAME APP | HOME</title>
            <meta name='description' content='Generated by create next app' />
            <meta
               name='viewport'
               content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <main>
            {data &&
               data.map((game: IGameProps) => {
                  return (
                     <>
                        <p key={game.id}>{game.name}</p>

                        <Link href={`/games/[id]`} as={`/games/${game.id}`}>
                           {game.background_image && (
                              <Image
                                 src={game.background_image}
                                 alt={`${game.name}`}
                                 width={100}
                                 height={100}
                                 style={{ objectFit: 'contain' }}
                              />
                           )}
                        </Link>
                     </>
                  );
               })}
         </main>
      </>
   );
}
